### ISSUE TITLE
Launcher can't access files even with storage permission

### ISSUE THREAD

**Issue by theophinetheodore** [bridgelauncher/launcher#9]
## Description

I have allowed the storage permission but Bridge can't seem to access the files.
The projection selection popup says 'This directory is empty'.
And creating new directories doesn't work.

But if I click 'Use this directory', Bridge main screen displays the following error: 'Bridge does not have permission to read the requested file.'

## Screenshots

![1722161359977](https://github.com/user-attachments/assets/4f8de4ee-267b-49fd-b412-f367114b874b)
![1722161359945](https://github.com/user-attachments/assets/e2147e8b-4038-4a4c-beca-16da6232a971)

## Affected App Version
 
0.0.3alpha

## Operating System

Android 10 (MIUI 12.0.19)

## Device Model

POCO C3 (angelicain)

**Comment by theothertored** [comment]
This is most likely due to improperly checking perms on Android 10 (it has both scoped storage and regular storage without the "manage external storage" permission). I'll publish a quick fix in a sec.

**Comment by theothertored** [comment]
Please update to this version and let me know if it fixed the problem.
https://github.com/bridgelauncher/launcher/releases/tag/v0.0.4-alpha

**Comment by theophinetheodore** [comment]
@theothertored it works! thank you so much, sir! 🫡

how can i return the favor? is it possible to donate to you? i don't have much right now, but i'll give you what i have.

**Comment by theophinetheodore** [comment]
By the way, I have a little doubt: I looked into the commits to see what you changed to make this permission thing work (I prolly won't understand it anyway), but I don't see any new commits, but you made a new release. How were you able to do that? I have no idea about how Android dev works.

**Comment by theothertored** [comment]
> is it possible to donate to you?

No, I don't wanna dox myself. Maybe at some point, when I finally get around to figuring out crypto.

> I don't see any new commits, but you made a new release.

That's bad source control on my part, the fix is (if I recall correctly) a 1 line change (`<=` to `<` for checking the Android version to determine whether to use regular storage perms or the external storage manager perm) which I did quickly for someone on the Discord server. I have an giant rework of the entire app in my working folder, and instead of making a separate branch I just stashed my work, did the fix, built the APK, sent it, then undone the fix because I changed permission checking in the rework anyway and didn't wanna deal with merging. Now I just published the same APK as a new release ASAP.

I should split master from the rework branch, reimplement the fix, delete this release and upload a new one so you can actually build the same APK from the source in the repo, sorry for that, I'll ping you in this issue when I get around to it.

**Comment by theothertored** [comment]
@TheoIsDumb I've finally gotten around to it lol
https://github.com/bridgelauncher/launcher/releases/tag/v0.0.5-alpha

**Comment by theophinetheodore** [comment]
@theothertored hey, thank you, brother!

btw, i made a theme for bridge launcher. it's pretty barebones, but i've been using it for a long time.
please do check it out: https://github.com/theoisdumb/launch2

**Comment by theothertored** [comment]
@TheoIsDumb cool design, very heartwarming to see Bridge getting some use :)
I like the status bar changing its foreground colour as the video changes, I wonder if that's hardcoded, built into Android or something custom?

**Comment by theophinetheodore** [comment]
@theothertored thanks! btw the color changing is built into android
